# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-16 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2017, 11, 16)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.date(2017, 11, 16)),
            preserve_default=False,
        ),
    ]
